/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reproductor;

import java.awt.Font;
import java.awt.HeadlessException;
import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import jaco.mp3.player.MP3Player;
import java.util.Collections;
import javax.swing.ImageIcon;
/**
 *
 * @author Keylor, Allison, Johan y Leandro 
 */
public class principal extends javax.swing.JFrame {

    int contador = 1;
    String cancion1 = "";
    String cancion2 = "";
    String cancion3 = "";
    String cancion4 = "";
    String cancion5 = "";
    String cancion6 = "";
    String cancion7 = "";
    
String c1 = "";
String c2 = "";
String c3 = "";
String c4 = "";
String c5 = "";
String c6 = "";
String c7 = "";

String nombre = "";
String n = "";
    
    MP3Player player = new MP3Player();
    reproductor r = new reproductor();
    
    ArrayList<String> nombres = new ArrayList<String>();
    String datos[] = new String[6];
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMusica = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JLabel();
        btnStop = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        labelLista = new javax.swing.JLabel();
        btnPause = new javax.swing.JLabel();
        btnPlay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtC1 = new javax.swing.JTextField();
        txtC2 = new javax.swing.JTextField();
        txtC3 = new javax.swing.JTextField();
        txtC4 = new javax.swing.JTextField();
        txtC5 = new javax.swing.JTextField();
        txtC6 = new javax.swing.JTextField();
        txtC7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMusicaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMusicaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMusica);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 120));

        btnEliminar.setText("Eliminar canción");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/img/salida.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/img/stop.png"))); // NOI18N
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopMouseClicked(evt);
            }
        });
        jPanel1.add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        btnCargar.setText("Cargar lista");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        labelLista.setFont(new java.awt.Font("Dubai", 0, 36)); // NOI18N
        labelLista.setForeground(new java.awt.Color(255, 255, 255));
        labelLista.setText("LISTA DE REPRODUCCIÓN");
        jPanel1.add(labelLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/img/pause.png"))); // NOI18N
        btnPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPauseMouseClicked(evt);
            }
        });
        jPanel1.add(btnPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/img/play.png"))); // NOI18N
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/img/fondo2 - copia.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtC1.setText("jTextField1");
        jPanel1.add(txtC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtC2.setText("jTextField1");
        jPanel1.add(txtC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtC3.setText("jTextField1");
        jPanel1.add(txtC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(txtC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, -1));

        txtC5.setText("jTextField1");
        jPanel1.add(txtC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        txtC6.setText("jTextField1");
        jPanel1.add(txtC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        txtC7.setText("jTextField1");
        jPanel1.add(txtC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        r.agregarElemento("C://Users/Keylor/Music/Black Veil Brides - In The End.mp3");
        r.agregarElemento("C://Users/Keylor/Music/Lil Nas X - Old Town Road (Official Video) ft. Billy Ray Cyrus.mp3");
        r.agregarElemento("C://Users/Keylor/Music/MGK - Invincible (Explicit) ft. Ester Dean.mp3");
        r.agregarElemento("C://Users/Keylor/Music/Matisse, Carin Leon - Como Lo Hice Yo.mp3");
        r.agregarElemento("C://Users/Keylor/Music/The Lumineers - Ho Hey.mp3");
        r.agregarElemento("C://Users/Keylor/Music/Hozier - Take Me To Church.mp3");
        r.agregarElemento("C://Users/Keylor/Music/Foster The People - Pumped Up Kicks.mp3");
        
        cancion1 = r.localizarElemento("C://Users/Keylor/Music/Black Veil Brides - In The End.mp3");
        cancion2 = r.localizarElemento("C://Users/Keylor/Music/Lil Nas X - Old Town Road (Official Video) ft. Billy Ray Cyrus.mp3");
        cancion3 = r.localizarElemento("C://Users/Keylor/Music/MGK - Invincible (Explicit) ft. Ester Dean.mp3");
        cancion4 = r.localizarElemento("C://Users/Keylor/Music/Matisse, Carin Leon - Como Lo Hice Yo.mp3");
        cancion5 = r.localizarElemento("C://Users/Keylor/Music/The Lumineers - Ho Hey.mp3");
        cancion6 = r.localizarElemento("C://Users/Keylor/Music/Hozier - Take Me To Church.mp3");
        cancion7 = r.localizarElemento("C://Users/Keylor/Music/Foster The People - Pumped Up Kicks.mp3");

        txtC1.setText(cancion1.substring(23));
        txtC2.setText(cancion2.substring(23));
        txtC3.setText(cancion3.substring(23));
        txtC4.setText(cancion4.substring(23)); 
        txtC5.setText(cancion5.substring(23)); 
        txtC6.setText(cancion6.substring(23));
        txtC7.setText(cancion7.substring(23));

        c1 = txtC1.getText();
        c2 = txtC2.getText();
        c3 = txtC3.getText();
        c4 = txtC4.getText();
        c5 = txtC5.getText();
        c6 = txtC6.getText();
        c7 = txtC7.getText();

        nombres.add(c1);
        nombres.add(c2);
        nombres.add(c3);
        nombres.add(c4);
        nombres.add(c5);
        nombres.add(c6);
        nombres.add(c7);

        Collections.sort(nombres);

        JTableHeader th;
        th = tablaMusica.getTableHeader();
        Font fuente = new Font("Cambria", Font.BOLD, 15);
        th.setFont(fuente);
        tablaMusica.setFont(new java.awt.Font("Cambria", 0, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Canciones");

        for(int i = 0; i < nombres.size(); i++){
            datos[0] = nombres.get(i);

            model.addRow(datos);
            tablaMusica.setModel(model);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaseleccionada = 0;

        try{

            filaseleccionada= tablaMusica.getSelectedRow();

            if (filaseleccionada==-1){

            }else{

                DefaultTableModel modelotabla=(DefaultTableModel) tablaMusica.getModel();

                nombre=(String)modelotabla.getValueAt(filaseleccionada, 0);

                n = nombre;
            }

        }catch (HeadlessException ex){
        }

        r.eliminarElemento(n);
        nombres.remove(filaseleccionada);

        JTableHeader th;
        th = tablaMusica.getTableHeader();
        Font fuente = new Font("Cambria", Font.BOLD, 15);
        th.setFont(fuente);
        tablaMusica.setFont(new java.awt.Font("Cambria", 0, 14));
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Canciones");

        for(int i = 0; i < nombres.size(); i++){
            datos[0] = nombres.get(i);

            model.addRow(datos);
            tablaMusica.setModel(model);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        player.addToPlayList(new File("C://Users/Keylor/Music/" + n));
        player.skipForward();
        //player.play();
        
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPauseMouseClicked
        // TODO add your handling code here:
        player.pause();
    }//GEN-LAST:event_btnPauseMouseClicked

    private void btnStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseClicked
        // TODO add your handling code here:
        player.stop();
    }//GEN-LAST:event_btnStopMouseClicked

    private void tablaMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMusicaMouseClicked
        // TODO add your handling code here:
        player.skipForward();
    }//GEN-LAST:event_tablaMusicaMouseClicked

    private void tablaMusicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMusicaMousePressed
        // TODO add your handling code here:
        int filaseleccionada;
        try{

            filaseleccionada= tablaMusica.getSelectedRow();

            if (filaseleccionada==-1){

            }else{

                DefaultTableModel modelotabla=(DefaultTableModel) tablaMusica.getModel();

                nombre =(String)modelotabla.getValueAt(filaseleccionada, 0);

                n = nombre;
            }

        }catch (HeadlessException ex){
        }

       
        System.out.println(n);
    }//GEN-LAST:event_tablaMusicaMousePressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        despedida d = new despedida();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel btnPause;
    private javax.swing.JLabel btnPlay;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLista;
    private javax.swing.JTable tablaMusica;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtC3;
    private javax.swing.JTextField txtC4;
    private javax.swing.JTextField txtC5;
    private javax.swing.JTextField txtC6;
    private javax.swing.JTextField txtC7;
    // End of variables declaration//GEN-END:variables
}
